# Generated by Django 4.2 on 2023-04-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0004_alter_newck_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
