# Generated by Django 4.2 on 2023-05-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0005_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(max_length=2000)),
                ('part1', models.CharField(max_length=2000)),
                ('part2', models.CharField(max_length=2000)),
                ('part3', models.CharField(max_length=2000)),
                ('image', models.ImageField(max_length=255, upload_to='images/')),
                ('video', models.CharField(max_length=2000)),
                ('questions', models.CharField(max_length=2000)),
            ],
        ),
    ]
