# Generated by Django 4.2 on 2023-05-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0006_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
    ]
