# Generated by Django 4.2 on 2023-05-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0007_remove_lesson_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proba', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.AlterField(
            model_name='answers',
            name='choice_text',
            field=models.CharField(max_length=20),
        ),
    ]
