# Generated by Django 4.2 on 2023-05-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0008_user_delete_lesson_alter_answers_choice_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=2000)),
                ('lastName', models.CharField(max_length=2000)),
                ('email', models.CharField(max_length=2000)),
                ('password', models.CharField(max_length=2000)),
                ('lc', models.CharField(choices=[('SG', 'Stari Grad'), ('CR', 'Centar'), ('NS', 'Novo Sarajevo'), ('NG', 'Novi Grad'), ('IL', 'Ilidža')], default='SG', max_length=10)),
                ('child', models.CharField(choices=[('Ima', 'Da'), ('Nema', 'Ne')], default='Nema', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
