# Generated by Django 4.2 on 2023-05-07 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0009_korisnik_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='KorisnikProgres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progres', models.IntegerField(default=0)),
                ('korisnikID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroj1.korisnik')),
            ],
        ),
    ]
