# Generated by Django 4.2 on 2023-05-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0010_korisnikprogres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lekcija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('subtitle1', models.CharField(max_length=2000)),
                ('part1', models.CharField(max_length=2000)),
                ('subtitle2', models.CharField(max_length=2000)),
                ('part2', models.CharField(max_length=2000)),
                ('subtitle3', models.CharField(max_length=2000)),
                ('part3', models.CharField(max_length=2000)),
                ('video', models.CharField(max_length=2000)),
            ],
        ),
    ]
