# Generated by Django 4.2 on 2023-05-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0013_blog_alter_lekcija_subtitle1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewCK',
            new_name='Obavjest',
        ),
    ]
