# Generated by Django 4.2 on 2023-05-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0014_rename_newck_obavjest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odgovor',
            name='pitanjeID',
        ),
        migrations.RemoveField(
            model_name='pitanje',
            name='lekcijaID',
        ),
        migrations.DeleteModel(
            name='Lekcija',
        ),
        migrations.DeleteModel(
            name='Odgovor',
        ),
        migrations.DeleteModel(
            name='Pitanje',
        ),
    ]
