# Generated by Django 4.2 on 2023-05-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0015_remove_odgovor_pitanjeid_remove_pitanje_lekcijaid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lekcija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('subtitle1', models.CharField(max_length=1000)),
                ('part1', models.CharField(max_length=2000)),
                ('subtitle2', models.CharField(max_length=2000)),
                ('part2', models.CharField(max_length=2000)),
                ('subtitle3', models.CharField(max_length=2000)),
                ('part3', models.CharField(max_length=2000)),
                ('video', models.CharField(max_length=2000)),
                ('image', models.ImageField(max_length=255, upload_to='images/')),
            ],
        ),
    ]
