# Generated by Django 4.2 on 2023-05-09 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0016_lekcija'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(max_length=2000)),
                ('lekcijaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroj1.lekcija')),
            ],
        ),
        migrations.CreateModel(
            name='Odgovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(max_length=2000)),
                ('pitanjeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroj1.pitanje')),
            ],
        ),
    ]
