# Generated by Django 4.2 on 2023-05-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0017_pitanje_odgovor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=2000)),
                ('opis', models.CharField(max_length=2000)),
                ('datum', models.DateTimeField(verbose_name='datum')),
                ('aktivno', models.BooleanField()),
                ('broj', models.IntegerField()),
                ('datum_kreiranja', models.DateTimeField(verbose_name='datum_kreiranja')),
                ('datum_promjene', models.DateTimeField(verbose_name='datum_promjene')),
            ],
        ),
    ]
