# Generated by Django 4.2 on 2023-05-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0018_greska'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greska',
        ),
    ]
