# Generated by Django 4.2 on 2023-05-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0019_delete_greska'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
