# Generated by Django 4.2.1 on 2023-05-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0023_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
