# Generated by Django 4.2.1 on 2023-05-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0025_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
