# Generated by Django 4.2.1 on 2023-05-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0026_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('subtitle1', models.CharField(max_length=2000)),
                ('part1', models.CharField(max_length=3500)),
                ('subtitle2', models.CharField(max_length=2000)),
                ('part2', models.CharField(max_length=3500)),
                ('subtitle3', models.CharField(max_length=2000)),
                ('part3', models.CharField(max_length=3500)),
                ('sadrzaj', models.CharField(max_length=3500)),
                ('image', models.ImageField(max_length=255, upload_to='Blog/')),
            ],
        ),
    ]
