# Generated by Django 4.2 on 2023-05-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0028_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='child',
            field=models.CharField(choices=[('Ima', 'Yes'), ('Nema', 'No')], default='Nema', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firstName',
            field=models.CharField(default='ime', max_length=2000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(default='prezime', max_length=2000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lc',
            field=models.CharField(choices=[('SG', 'Stari Grad'), ('CR', 'Centar'), ('NS', 'Novo Sarajevo'), ('NG', 'Novi Grad'), ('IL', 'Ilidža')], default='SG', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='progres',
            field=models.IntegerField(default=0),
        ),
    ]
