# Generated by Django 4.2 on 2023-05-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0029_remove_userprofile_city_userprofile_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='email', max_length=2000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='child',
            field=models.CharField(choices=[('Da', 'Yes'), ('Ne', 'No')], default='Ne', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lc',
            field=models.CharField(choices=[('Stari grad', 'Stari Grad'), ('Centar', 'Centar'), ('Novo Sarajevo', 'Novo Sarajevo'), ('Novi grad', 'Novi Grad'), ('Ilidža', 'Ilidža')], default='Stari grad', max_length=2000),
        ),
    ]
