# Generated by Django 4.2.1 on 2023-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0030_userprofile_email_alter_userprofile_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekcija',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
