# Generated by Django 4.2.1 on 2023-05-26 11:16

import django.core.validators
from django.db import migrations, models
import heroj1.models


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0031_alter_lekcija_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekcija',
            name='video',
            field=models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), heroj1.models.validate_mp4]),
        ),
    ]
