# Generated by Django 4.2.1 on 2023-06-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroj1', '0034_kvizrezultati'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnikprogres',
            name='korisnikID',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Korisnik',
        ),
        migrations.DeleteModel(
            name='KorisnikProgres',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
